jobs:
  build:
    docker:
      - image: mukundvvdn/new
        auth:
          username: mukundvvdn  # can specify string literal values
          password: Mukund@123  # or project UI environment variable reference
